### ISSUE TITLE
Create stand-alone flask tests

### ISSUE THREAD

**Issue by jbcoe** [FFIG/rest-api#19]
Flask apps can be tested without using Docker. This would potentially be simpler to maintain/run.

http://flask.pocoo.org/docs/0.12/testing/

**Comment by petr-tik** [comment]
I understand the difficulty of using docker. 

Isn't it better to use the advantage of docker (dev = prod) and test in the same environment as we want to run it?

**Comment by jbcoe** [comment]
We definitely want integration testing where we do use Docker. Just pondering if a lighter testing environment might speed up work. Totally your call.

**Comment by petr-tik** [comment]
The way I see it.

Docker Pros

- Use ffig-base and easily import deps and ffig repo
- Keep the same environment between dev, test and prod

Docker Cons

- Networking can be a pain
- Heavy-duty for unit tests

Let me try unit tests in Docker and if it doesn't work out, will scrap it and write unit tests without it

**Comment by petr-tik** [comment]
[This travis CI job](https://travis-ci.org/FFIG/rest-api/builds/370809489) takes 3m11s, of which 
docker pull takes 142.56s
docker build takes 27.88s

Looking ahead to possible deployment scenarios - AWS Lambda (not confirmed if we are using iut yet though) doesn't support docker and takes Python programmes instead. 

Overall with a potentially Dockerless prod environment, it makes sense to get rid of docker for testing
